function D = death_costs(c_d, u_1, v_1, opt_T1, z, v_0, delta_1,delta_2, u_0)

D = c_d .* ( ( ((u_1 - v_1 .* (opt_T1)) ./ z ) + (v_1 ./z.^2) ) .* exp(z.*(opt_T1)) ... 
                 - (v_0./z.^2) .* exp(z.* delta_1) ...
                 - (v_1./z.^2) .* exp(z.* delta_2) ...
                  + (v_0./z.^2) ... 
                 - (u_0/z) ...
                 + (v_0.*delta_1.^2) ./ (2)  ...
                 + (v_1./ (2)) .* ( (opt_T1).^2 + delta_2.^2 ) ...
                 - (u_1 .* (opt_T1) ) )

end
