function H  = Holding_costs(c_h, u_1, v_1, T1, z, delta_1, delta_2, ...
                            v_0, u_0 )

 H  = c_h .* ( (((u_1 - (v_1 .* T1)) ./ z.^2 ) + (v_1 ./z.^3)) .* exp(z.*T1) ...
        - (v_0 ./ z.^3) .* exp(z.* delta_1)...
      - (v_1./z.^3) .* exp(z.* delta_2)...
       + (v_0./z.^3)...
       - (u_0 ./ z.^2) ...
      + (v_0.* delta_1.^2)./ (2.*z)  ...
      + (v_1./ (2.*z)) .* ( (T1).^2 + delta_2.^2 ) ...
      - (u_1 .* (T1))/z )
end 
