function S = shortage_costs(c_s, u_1, v_1, opt_T1, n, T )

S = c_s .* ( ((u_1 ./ n.^2) +  ((2.*v_1) ./ n.^3 ))  * (1 - exp( n .* ((opt_T1)- T) ) ) ...
             + ((u_1 ./ n) +  ((v_1)/n.^2 ) ).*( (opt_T1) - T ).*exp( n .* ((opt_T1)- T) ) ...
             + (v_1./n).*(T - (opt_T1)).*(opt_T1).*exp(n.* ((opt_T1)- T)) ...
             - (v_1 ./ n.^2).* (T - (opt_T1).* exp(n.* ((opt_T1)- T))) )

end 
